#ifndef PHONE_H
#define PHONE_H

#define FALSE                                            0
#define TURE                                             1

#define KBL1                                             13
#define KBL2                                             14
#define KBL3                                             13
#define KBL4                                             12
#define KBL5                                             6

#define IDC_WINDOW_TIME					 101

#define IDC_MENU_BUTTON1				 151
#define IDC_MENU_BUTTON2				 152
#define IDC_MENU_BUTTON3				 153
#define IDC_MENU_BUTTON4				 154
#define IDC_MENU_BUTTON5				 155
#define IDC_MENU_BUTTON6				 156
#define IDC_MENU_BUTTON7				 157
#define IDC_MENU_BUTTON8				 158
#define IDC_MENU_BUTTON9				 159

#define IDC_AD_SAVE					 251
#define IDC_AD_BACK					 252
#define IDC_AD_STATIC_AIR				 253
#define IDC_AD_STATIC_SOIL				 254
#define IDC_AD_STATIC_WATER				 255
#define IDC_AD_SLEDIT_AIR				 256
#define IDC_AD_SLEDIT_SOIL				 257
#define IDC_AD_SLEDIT_WATER				 258
#define IDC_AD_CATCH					 259

#define IDC_GPRS_TEL_TIME_MENU_STATIC_ALL		 301
#define IDC_GPRS_TEL_TIME_MENU_STATIC_CALL		 302
#define IDC_GPRS_TEL_TIME_MENU_STATIC_BECALL		 303
#define IDC_GPRS_TEL_TIME_MENU_STATIC_LASTCALL		 304
#define IDC_GPRS_TEL_TIME_MENU_SLEDIT_ALL		 305
#define IDC_GPRS_TEL_TIME_MENU_SLEDIT_CALL		 306
#define IDC_GPRS_TEL_TIME_MENU_SLEDIT_BECALL		 307
#define IDC_GPRS_TEL_TIME_MENU_SLEDIT_LASTCALL		 308
#define IDC_GPRS_TEL_TIME_MENU_BUTTON_CLEAR		 309
#define IDC_GPRS_TEL_TIME_MENU_BUTTON_CLOSE		 310

#define IDC_GPRS_TEL_MENU_BUTTON_CALL			 351
#define IDC_GPRS_TEL_MENU_BUTTON_NOGET			 352
#define IDC_GPRS_TEL_MENU_BUTTON_GET			 353
#define IDC_GPRS_TEL_MENU_BUTTON_DIAL			 354
#define IDC_GPRS_TEL_MENU_BUTTON_TIME			 355
#define IDC_GPRS_TEL_MENU_BUTTON_CLOSE			 356

#define IDC_GPRS_TEL_CALL_STATIC_TELNUMBER		 357
#define IDC_GPRS_TEL_CALL_SLEDIT_TELNUMBER		 358
#define IDC_GPRS_TEL_CALL_BUTTON_CALL			 359
#define IDC_GPRS_TEL_CALL_BUTTON_HANGUP			 360
#define IDC_GPRS_TEL_CALL_BUTTON_TELBOOK		 361
#define IDC_GPRS_TEL_CALL_BUTTON_CLOSE			 362

#define IDC_GPRS_TEL_CALLING_STATIC_NAME		 363
#define IDC_GPRS_TEL_CALLING_STATIC_TELNUMBER		 364
#define IDC_GPRS_TEL_CALLING_STATIC_STATE		 365
#define IDC_GPRS_TEL_CALLING_STATIC_TIME		 366
#define IDC_GPRS_TEL_CALLING_BUTTON_HANGUP		 367

#define IDC_GPRS_TEL_BECALLING_STATIC_NUMBER		 366
#define IDC_GPRS_TEL_BECALLING_BUTTON_GET		 367
#define IDC_GPRS_TEL_BECALLING_BUTTON_NOGET		 370

#define IDC_GPRS_TEL_BECALLINGGET_STATIC_NAME		 371
#define IDC_GPRS_TEL_BECALLINGGET_STATIC_NUMBER		 372
#define IDC_GPRS_TEL_BECALLINGGET_STATIC_STATE		 373
#define IDC_GPRS_TEL_BECALLINGGET_STATIC_TIME		 374
#define IDC_GPRS_TEL_BECALLINGGET_BUTTON_RINGOFF	 375

#define IDC_GPRS_TEL_SHOWTELDIAL_LISTBOX_NUMBER		 376
#define IDC_GPRS_TEL_SHOWTELDIAL_LISTBOX_TIME		 377
#define IDC_GPRS_TEL_SHOWTELDIAL_BUTTON_SHOW		 378
#define IDC_GPRS_TEL_SHOWTELDIAL_BUTTON_CLEAR		 379
#define IDC_GPRS_TEL_SHOWTELDIAL_BUTTON_DEL		 380
#define IDC_GPRS_TEL_SHOWTELDIAL_BUTTON_CLOSE		 381
#define IDC_GPRS_TEL_SHOWTELDIAL_STATIC_CALLTIME	 382
#define IDC_GPRS_TEL_SHOWTELDIAL_SLEDIT_CALLTIME	 383

#define IDC_GPRS_TEL_SHOWTELGET_LISTBOX_NUMBER		 384
#define IDC_GPRS_TEL_SHOWTELGET_LISTBOX_TIME		 385
#define IDC_GPRS_TEL_SHOWTELGET_BUTTON_SHOW		 386
#define IDC_GPRS_TEL_SHOWTELGET_BUTTON_CLEAR		 387
#define IDC_GPRS_TEL_SHOWTELGET_BUTTON_DEL		 388
#define IDC_GPRS_TEL_SHOWTELGET_BUTTON_CLOSE		 389
#define IDC_GPRS_TEL_SHOWTELGET_STATIC_CALLTIME		 390
#define IDC_GPRS_TEL_SHOWTELGET_SLEDIT_CALLTIME		 391

#define IDC_GPRS_TEL_SHOWTELNOGET_LISTBOX_NUMBER	 392
#define IDC_GPRS_TEL_SHOWTELNOGET_LISTBOX_TIME		 393
#define IDC_GPRS_TEL_SHOWTELNOGET_BUTTON_SHOW		 394
#define IDC_GPRS_TEL_SHOWTELNOGET_BUTTON_CLEAR		 395
#define IDC_GPRS_TEL_SHOWTELNOGET_BUTTON_DEL		 396
#define IDC_GPRS_TEL_SHOWTELNOGET_BUTTON_CLOSE		 397

#define IDC_GPRS_MESSAGE_BUTTON_NEW			 401
#define IDC_GPRS_MESSAGE_BUTTON_INBOX			 402
#define IDC_GPRS_MESSAGE_BUTTON_OUTBOX			 403
#define IDC_GPRS_MESSAGE_BUTTON_DRAFT			 404
#define IDC_GPRS_MESSAGE_BUTTON_SOS			 405
#define IDC_GPRS_MESSAGE_BUTTON_CLOSE			 406

#define IDC_GPRS_MESSAGE_NEW_BUTTON_SEND		 407
#define IDC_GPRS_MESSAGE_NEW_BUTTON_SAVE		 408
#define IDC_GPRS_MESSAGE_NEW_BUTTON_CLOSE		 409
#define IDC_GPRS_MESSAGE_NEW_STATIC_TEXT		 410
#define IDC_GPRS_MESSAGE_NEW_STATIC_NUMBER		 411
#define IDC_GPRS_MESSAGE_NEW_SLEDIT_NUMBER		 412
#define IDC_GPRS_MESSAGE_NEW_SLEDIT_TEXT		 413

#define IDC_GPRS_MESSAGE_DRAFT_LISTBOX_NUMBER		 414
#define IDC_GPRS_MESSAGE_DRAFT_LISTBOX_TIME		 415
#define IDC_GPRS_MESSAGE_DRAFT_BUTTON_SHOW		 416
#define IDC_GPRS_MESSAGE_DRAFT_BUTTON_DEL		 417
#define IDC_GPRS_MESSAGE_DRAFT_BUTTON_CLOSE		 418
#define IDC_GPRS_MESSAGE_DRAFT_BUTTON_CLEAR		 419

#define IDC_GPRS_MESSAGE_OUTBOX_LISTBOX_NUMBER		 420
#define IDC_GPRS_MESSAGE_OUTBOX_LISTBOX_TIME		 421
#define IDC_GPRS_MESSAGE_OUTBOX_BUTTON_SHOW		 422
#define IDC_GPRS_MESSAGE_OUTBOX_BUTTON_DEL		 423
#define IDC_GPRS_MESSAGE_OUTBOX_BUTTON_CLOSE		 424
#define IDC_GPRS_MESSAGE_OUTBOX_BUTTON_CLEAR		 425

#define IDC_GPRS_MESSAGE_DRAFT_SHOW_STATIC_NUMBER	 426
#define IDC_GPRS_MESSAGE_DRAFT_SHOW_STATIC_TEXT		 427
#define IDC_GPRS_MESSAGE_DRAFT_SHOW_SLEDIT_NUMBER	 428
#define IDC_GPRS_MESSAGE_DRAFT_SHOW_SLEDIT_TEXT		 429
#define IDC_GPRS_MESSAGE_DRAFT_SHOW_BUTTON_REWORK	 430
#define IDC_GPRS_MESSAGE_DRAFT_SHOW_BUTTON_QUIT		 431
#define IDC_GPRS_MESSAGE_DRAFT_SHOW_BUTTON_SEND		 432

#define IDC_GPRS_MESSAGE_OUTBOX_SHOW_STATIC_NUMBER	 433
#define IDC_GPRS_MESSAGE_OUTBOX_SHOW_STATIC_TEXT	 434
#define IDC_GPRS_MESSAGE_OUTBOX_SHOW_SLEDIT_NUMBER	 435
#define IDC_GPRS_MESSAGE_OUTBOX_SHOW_SLEDIT_TEXT	 436
#define IDC_GPRS_MESSAGE_OUTBOX_SHOW_BUTTON_REWORK	 437
#define IDC_GPRS_MESSAGE_OUTBOX_SHOW_BUTTON_SEND	 438
#define IDC_GPRS_MESSAGE_OUTBOX_SHOW_BUTTON_QUIT	 439

#define IDC_GPRS_TELBOOK_LISTBOX_NAME			 451
#define IDC_GPRS_TELBOOK_LISTBOX_NUMBER			 452
#define IDC_GPRS_TELBOOK_BUTTON_SHOW			 453
#define IDC_GPRS_TELBOOK_BUTTON_ADD			 454
#define IDC_GPRS_TELBOOK_BUTTON_DEL			 455
#define IDC_GPRS_TELBOOK_BUTTON_CLOSE			 456
#define IDC_GPRS_TELBOOK_BUTTON_CALL			 457

#define IDC_GPRS_TELBOOK_ADD_STATIC_NUMBER		 458
#define IDC_GPRS_TELBOOK_ADD_STATIC_NAME		 459
#define IDC_GPRS_TELBOOK_ADD_SLEDIT_NAME		 460
#define IDC_GPRS_TELBOOK_ADD_SLEDIT_NUMBER		 461
#define IDC_GPRS_TELBOOK_ADD_BUTTON_CREAT		 462
#define IDC_GPRS_TELBOOK_ADD_BUTTON_QUIT		 463

#define IDC_GPRS_TELBOOK_SHOW_STATIC_NAME		 464
#define IDC_GPRS_TELBOOK_SHOW_STATIC_NUMBER		 465
#define IDC_GPRS_TELBOOK_SHOW_SLEDIT_NAME		 466
#define IDC_GPRS_TELBOOK_SHOW_SLEDIT_NUMBER		 467
#define IDC_GPRS_TELBOOK_SHOW_BUTTON_REWORK		 468
#define IDC_GPRS_TELBOOK_SHOW_BUTTON_QUIT		 469

#define IDC_SYSTEM_MENU_BUTTON_TIME			 501
#define IDC_SYSTEM_MENU_BUTTON_REGARD			 502
#define IDC_SYSTEM_MENU_BUTTON_INFO			 503
#define IDC_SYSTEM_MENU_BUTTON_CLOSE			 504
#define IDC_SYSTEM_SETTIME_SLEDIT_YEAR			 505
#define IDC_SYSTEM_SETTIME_STATIC_YEAR			 506
#define IDC_SYSTEM_SETTIME_SLEDIT_MONTH			 507
#define IDC_SYSTEM_SETTIME_STATIC_MONTH			 508
#define IDC_SYSTEM_SETTIME_SLEDIT_DATA			 509
#define IDC_SYSTEM_SETTIME_STATIC_DATA			 510
#define IDC_SYSTEM_SETTIME_SLEDIT_HOUR			 511
#define IDC_SYSTEM_SETTIME_STATIC_HOUR			 512
#define IDC_SYSTEM_SETTIME_SLEDIT_MINUTE		 513
#define IDC_SYSTEM_SETTIME_STATIC_MINUTE		 514
#define IDC_SYSTEM_SETTIME_SLEDIT_SECOND		 515
#define IDC_SYSTEM_SETTIME_STATIC_SECOND		 516
#define IDC_SYSTEM_SETTIME_BUTTON_REWORK		 517
#define IDC_SYSTEM_SETTIME_BUTTON_QUIT			 518
#define IDC_SYSTEM_SETREGARD_STATIC_REGARD		 519
#define IDC_SYSTEM_SETREGARD_SLEDIT_REGARD		 520
#define IDC_STSTEM_SETREGARD_BUTTON_REWORK		 521
#define IDC_STSTEM_SETREGARD_BUTTON_QUIT		 522

#define IDC_SYSTEM_SETUSERINFO_STATIC_NAME		 523
#define IDC_SYSTEM_SETUSERINFO_STATIC_NUMBER		 524
#define IDC_SYSTEM_SETUSERINFO_SLEDIT_NAME		 525
#define IDC_SYSTEM_SETUSERINFO_SLEDIT_NUMBER		 526
#define IDC_SYSTEM_SETUSERINFO_BUTTON_REWORK		 527
#define IDC_SYSTEM_SETUSERINFO_BUTTON_QUIT		 528

#define IDC_FUN_MENU_BUTTON_MPLAYER			 551
#define IDC_FUN_MENU_BUTTON_BOMB			 552
#define IDC_FUN_MENU_BUTTON_CLOSE			 553

#define IDC_FUN_BOMB_NEW				 554
#define IDC_FUN_BOMB_SMALL				 555
#define IDC_FUN_BOMB_CLOSE				 556
#define IDC_FUN_BOMB_CLOCK				 557
#define IDC_FUN_BOMB_BUTTON_SHAO			 558
#define IDC_FUN_BOMB_BUTTON_BIAO			 559
#define IDC_FUN_BOMB_BUTTON_HIGHSCORE			 560
#define IDC_FUN_BOMB_BUTTON_CLOSE			 561
#define IDC_FUN_BOMB_SAVE_BUTTON_OK			 562
#define IDC_FUN_BOMB_SAVE_BUTTON_CLOSE			 563
#define IDC_FUN_BOMB_SAVE_STATIC_NAME			 564
#define IDC_FUN_BOMB_SAVE_SLEDIT_NAME			 565

#define IDC_FUN_BOMB_HIGHSORE_STATIC_NAME		 566
#define IDC_FUN_BOMB_HIGHSORE_STATIC_RESULT		 567
#define IDC_FUN_BOMB_HIGHSORE_LISTBOX_NAME		 568
#define IDC_FUN_BOMB_HIGHSORE_LISTBOX_RESULT		 569
#define IDC_FUN_BOMB_HIGHSORE_BUTTON_CLEAR		 570
#define IDC_FUN_BOMB_HIGHSORE_BUTTON_CLOSE		 571

#define IDC_FUN_MPLAYER_BUTTON_ADD			 601
#define IDC_FUN_MPLAYER_BUTTON_CLOSE			 602
#define IDC_FUN_MPLAYER_BUTTON_DEL			 603
#define IDC_FUN_MPLAYER_BUTTON_PLAY			 604
#define IDC_FUN_MPLAYER_BUTTON_STAY			 605
#define IDC_FUN_MPLAYER_BUTTON_STOP			 606
#define IDC_FUN_MPLAYER_LISTBOX_NAME			 607
#define IDC_FUN_MPLAYER_LISTBOX_SINGER			 608

#define IDC_FUN_MPLAYER_MUSICADD_STATIC_DIR		 609
#define IDC_FUN_MPLAYER_MUSICADD_STATIC_FILE		 610
#define IDC_FUN_MPLAYER_MUSICADD_LISTBOX_DIR		 611
#define IDC_FUN_MPLAYER_MUSICADD_LISTBOX_FILE		 612
#define IDC_FUN_MPLAYER_MUSICADD_STATIC_PATH		 613
#define IDC_FUN_MPLAYER_MUSICADD_BUTTON_CHOOSE		 614
#define IDC_FUN_MPLAYER_MUSICADD_BUTTON_CANCEL		 615
#define IDC_FUN_MPLAYER_MUSICADD_SLEDIT_NAME		 616
#define IDC_FUN_MPLAYER_MUSICADD_SLEDIT_SINGER		 617


#define IDC_FUN_3G_BUTTON_CONNECT			 650
#define IDC_FUN_3G_BUTTON_CLOSE			 	 651
#define IDC_FUN_3G_ADD_LISTBOX_FILE		 	652
#define IDC_FUN_3G_NOW_LISTBOX_FILE		 	653

#define IDC_TOOLS_MENU_BUTTON_CLOSE			 701
#define IDC_TOOLS_MENU_BUTTON_MEMOIRE			 702
#define IDC_TOOLS_MENU_BUTTON_ALARMCLOCK		 703
#define IDC_TOOLS_MENU_BUTTON_NOTEPAD			 704
#define IDC_TOOLS_MENU_BUTTON_CALENDAR			 705
#define IDC_TOOLS_MENU_BUTTON_CALCULATO			 706
#define	IDC_TOOLS_MENU_BUTTON_EXPLORE			 707

#define IDC_TOOLS_NOTEPAD_LISTBOX_TITLE			 708
#define IDC_TOOLS_NOTEPAD_LISTBOX_TIME			 709
#define IDC_TOOLS_NOTEPAD_BUTTON_SHOW			 710
#define IDC_TOOLS_NOTEPAD_BUTTON_ADD			 711
#define IDC_TOOLS_NOTEPAD_BUTTON_DEL			 712
#define IDC_TOOLS_NOTEPAD_BUTTON_CLOSE			 713

#define IDC_TOOLS_NOTEPAD_ADD_STATIC_TITLE		 714
#define IDC_TOOLS_NOTEPAD_ADD_STATIC_TEXT		 715
#define IDC_TOOLS_NOTEPAD_ADD_SLEDIT_TITLE		 716
#define IDC_TOOLS_NOTEPAD_ADD_SLEDIT_TEXT		 717
#define IDC_TOOLS_NOTEPAD_ADD_BUTTON_CREAT		 718
#define IDC_TOOLS_NOTEPAD_ADD_BUTTON_QUIT		 719

#define IDC_TOOLS_NOTEPAD_SHOW_STATIC_TITLE		 720
#define IDC_TOOLS_NOTEPAD_SHOW_STATIC_TEXT		 721
#define IDC_TOOLS_NOTEPAD_SHOW_SLEDIT_TITLE		 722
#define IDC_TOOLS_NOTEPAD_SHOW_SLEDIT_TEXT		 723
#define IDC_TOOLS_NOTEPAD_SHOW_BUTTON_REWORK		 724
#define IDC_TOOLS_NOTEPAD_SHOW_BUTTON_QUIT		 725

#define IDC_TOOLS_CALENDAR_CTRL_CALENDAR		 726
#define IDC_TOOLS_CALENDAR_BUTTON_CLOSE			 727

#define IDC_TOOLS_ALARMCLOCK_LISTBOX_TIME		 751
#define IDC_TOOLS_ALARMCLOCK_LISTBOX_MODE		 752
#define IDC_TOOLS_ALARMCLOCK_BUTTON_ADD			 753
#define IDC_TOOLS_ALARMCLOCK_BUTTON_DEL			 754
#define IDC_TOOLS_ALARMCLOCK_BUTTON_CLOSE		 755
#define IDC_TOOLS_ALARMCLOCK_ADD_STATIC_TIME		 756
#define IDC_TOOLS_ALARMCLOCK_ADD_SLEDIT_YEAR		 757
#define IDC_TOOLS_ALARMCLOCK_ADD_STATIC_YEAR		 758
#define IDC_TOOLS_ALARMCLOCK_ADD_SLEDIT_MONTH		 759
#define IDC_TOOLS_ALARMCLOCK_ADD_STATIC_MONTH		 760
#define IDC_TOOLS_ALARMCLOCK_ADD_SLEDIT_DATA		 761
#define IDC_TOOLS_ALARMCLOCK_ADD_STATIC_DATA		 762
#define IDC_TOOLS_ALARMCLOCK_ADD_SLEDIT_HOUR		 763
#define IDC_TOOLS_ALARMCLOCK_ADD_STATIC_HOUR		 764
#define IDC_TOOLS_ALARMCLOCK_ADD_SLEDIT_MINUTE		 765
#define IDC_TOOLS_ALARMCLOCK_ADD_STATIC_MINUTE		 766
#define IDC_TOOLS_ALARMCLOCK_ADD_STATIC_DURATION	 767
#define IDC_TOOLS_ALARMCLOCK_ADD_SLEDIT_DURATION	 768
#define IDC_TOOLS_ALARMCLOCK_ADD_STATIC_DMINUTE		 769
#define IDC_TOOLS_ALARMCLOCK_ADD_STATIC_MODE		 770
#define IDC_TOOLS_ALARMCLOCK_ADD_BUTTON_CREAT		 771
#define IDC_TOOLS_ALARMCLOCK_ADD_BUTTON_QUIT		 772
#define IDC_TOOLS_ALARMCLOCK_ADD_COMBOBOX_MODE		 773

#define IDC_TOOLS_MEMOIRE_LISTBOX_TITLE			 801
#define IDC_TOOLS_MEMOIRE_LISTBOX_TIME			 802
#define IDC_TOOLS_MEMOIRE_BUTTON_SHOW			 803
#define IDC_TOOLS_MEMOIRE_BUTTON_ADD			 804
#define IDC_TOOLS_MEMOIRE_BUTTON_DEL			 805
#define IDC_TOOLS_MEMOIRE_BUTTON_REWORK			 806
#define IDC_TOOLS_MEMOIRE_BUTTON_CLOSE			 807

#define IDC_TOOLS_MEMOIRE_ADD_STATIC_TITLE		 808
#define IDC_TOOLS_MEMOIRE_ADD_STATIC_TEXT		 809
#define IDC_TOOLS_MEMOIRE_ADD_SLEDIT_TITLE		 810
#define IDC_TOOLS_MEMOIRE_ADD_SLEDIT_TEXT		 811
#define IDC_TOOLS_MEMOIRE_ADD_BUTTON_CREAT		 812
#define IDC_TOOLS_MEMOIRE_ADD_BUTTON_QUIT		 813
#define IDC_TOOLS_MEMOIRE_ADD_STATIC_YEAR		 814
#define IDC_TOOLS_MEMOIRE_ADD_STATIC_MONTH		 815
#define IDC_TOOLS_MEMOIRE_ADD_STATIC_DATA		 816
#define IDC_TOOLS_MEMOIRE_ADD_STATIC_HOUR		 817
#define IDC_TOOLS_MEMOIRE_ADD_STATIC_MINUTE		 818
#define IDC_TOOLS_MEMOIRE_ADD_SLEDIT_YEAR		 819
#define IDC_TOOLS_MEMOIRE_ADD_SLEDIT_MONTH		 820
#define IDC_TOOLS_MEMOIRE_ADD_SLEDIT_DATA		 821
#define IDC_TOOLS_MEMOIRE_ADD_SLEDIT_HOUR		 822
#define IDC_TOOLS_MEMOIRE_ADD_SLEDIT_MINUTE		 823

#define IDC_TOOLS_MEMOIRE_SHOW_STATIC_TITLE		 824
#define IDC_TOOLS_MEMOIRE_SHOW_STATIC_TEXT		 825
#define IDC_TOOLS_MEMOIRE_SHOW_SLEDIT_TITLE		 826
#define IDC_TOOLS_MEMOIRE_SHOW_SLEDIT_TEXT		 827
#define IDC_TOOLS_MEMOIRE_SHOW_STATIC_YEAR		 828
#define IDC_TOOLS_MEMOIRE_SHOW_STATIC_MONTH		 829
#define IDC_TOOLS_MEMOIRE_SHOW_STATIC_DATA		 830
#define IDC_TOOLS_MEMOIRE_SHOW_STATIC_HOUR		 831
#define IDC_TOOLS_MEMOIRE_SHOW_STATIC_MINUTE		 832
#define IDC_TOOLS_MEMOIRE_SHOW_SLEDIT_YEAR		 833
#define IDC_TOOLS_MEMOIRE_SHOW_SLEDIT_MONTH		 834
#define IDC_TOOLS_MEMOIRE_SHOW_SLEDIT_DATA		 835
#define IDC_TOOLS_MEMOIRE_SHOW_SLEDIT_HOUR		 836
#define IDC_TOOLS_MEMOIRE_SHOW_SLEDIT_MINUTE		 837
#define IDC_TOOLS_MEMOIRE_SHOW_BUTTON_REWORK		 838
#define IDC_TOOLS_MEMOIRE_SHOW_BUTTON_QUIT		 839

#define IDC_TOOLS_EXPLORER_LISTBOX_DIR			 840
#define IDC_TOOLS_EXPLORER_LISTBOX_FILE			 841
#define IDC_TOOLS_EXPLORER_STATIC_PATH			 842
#define IDC_TOOLS_EXPLORER_STATIC_DIR			 843
#define IDC_TOOLS_EXPLORER_STATIC_FILE			 844
#define IDC_TOOLS_EXPLORER_BUTTON_DEL			 845
#define IDC_TOOLS_EXPLORER_BUTTON_QUIT			 846

#define IDC_TOOLS_CALCULATOR_1                           851
#define IDC_TOOLS_CALCULATOR_2                           852
#define IDC_TOOLS_CALCULATOR_3                           853
#define IDC_TOOLS_CALCULATOR_4                           854
#define IDC_TOOLS_CALCULATOR_5                           855
#define IDC_TOOLS_CALCULATOR_6                           856
#define IDC_TOOLS_CALCULATOR_7                           857
#define IDC_TOOLS_CALCULATOR_8                           858
#define IDC_TOOLS_CALCULATOR_9                           859
#define IDC_TOOLS_CALCULATOR_0                           860
#define IDC_TOOLS_CALCULATOR_C                           861
#define IDC_TOOLS_CALCULATOR_ADD                         862
#define IDC_TOOLS_CALCULATOR_SUB                         863
#define IDC_TOOLS_CALCULATOR_MUL                         864
#define IDC_TOOLS_CALCULATOR_CHU                         865
#define IDC_TOOLS_CALCULATOR_CALCULATE                   866
#define IDC_TOOLS_CALCULATOR_POINT                       867
#define IDC_TOOLS_CALCULATOR_SIGN                        868
#define IDC_TOOLS_CALCULATOR_SEXPRESSION                 869
#define IDC_TOOLS_CALCULATOR_EEXPRESSION                 870


#define IDC_TASKBAR_KB_CB				 951
#define IDC_TASKBAR_KB_CAPS				 952
#define IDC_TASKBAR_KB_LSHIFT				 953
#define IDC_TASKBAR_KB_RSHIFT				 954
#define IDC_TASKBAR_KB_LCTRL				 955
#define IDC_TASKBAR_KB_RCTRL				 956
#define IDC_TASKBAR_KB_LALT				 967
#define IDC_TASKBAR_KB_RALT				 958

#define IDC_TASKBAR_TASKBAR_MENU			 1001
#define IDC_TASKBAR_TASKBAR_CHANGEWINDOW		 1002
#define IDC_TASKBAR_TASKBAR_INPUT			 1003

#define MSG_TASKBAR_CLOSE				 1101
#define MSG_TASKBARMENU_CLOSE				 1102
#define MSG_CONTACTS_CALL				 1103
#define MSG_CALL_NUMBER					 1104
#define MSG_REWORK_LIST					 1105
#define MSG_MEMOIRE_ADD					 1106
#define MSG_MEMOIRE_TIME_OVER				 1107
#define MSG_FUN_BOMB_HIGHSCORE				 1108
#define MSG_BOMB_SAVE					 1109
#define MSG_MUSIC_ADD					 1110
#define MSG_TEL_CALL					 1111
#define MSG_RING					 1112
#define MSG_RING_HOLD					 1113
#define MSG_NOTEPAD_ADD					 1114
#define MSG_ALARMCLOCK_ADD				 1115
#define MSG_TELBOOK_ADD					 1116
#define MSG_TELBOOK_CALL				 1117
#define MSG_MESSAGE_DRAFT_REWORK			 1118
#define MSG_MESSAGE_OUTBOX_REWORK			 1119
#define MSG_CLOCK_TIME_OVER				 1120
#define MSG_BECALLING_CLOSE				 1121



#define	IDC_XZ_USRX		1400
#define	IDC_XZ_PWDX		IDC_XZ_USRX+ 1
#define	IDC_XZ_USR		IDC_XZ_USRX+ 2
#define	IDC_XZ_PWD		IDC_XZ_USRX+ 3
#define	IDC_XZ_APNX		IDC_XZ_USRX+ 4
#define	IDC_XZ_APN		IDC_XZ_USRX+ 5
#define	IDC_XZ_PHONEX		IDC_XZ_USRX+ 6
#define	IDC_XZ_PHONE		IDC_XZ_USRX+ 7
#define	IDC_XZ_RETURN		IDC_XZ_USRX+ 8
#define	IDC_XZ_SET		IDC_XZ_USRX+ 9
#define	IDC_XZ_CONNECT		IDC_XZ_USRX+10
#define	IDC_XZ_OK		IDC_XZ_USRX+11
#define	IDC_XZ_CANCEL		IDC_XZ_USRX+12
#define	IDC_XZ_DISCONNECT	IDC_XZ_USRX+13
#define	IDC_XZ_CONNECT_CANCEL	IDC_XZ_USRX+14
#define	IDC_XZ_CLOSE         	IDC_XZ_USRX+15


#define IDC_3G_DIR          1480
#define IDC_3G_FILE         1481
#define IDC_3G_PATH         1482
#define IDC_3G_DOWNLOAD     1483
#define IDC_3G_RETURN       1484

#define	IDC_NETWORK_USRX		1600
#define	IDC_NETWORK_PWDX		IDC_NETWORK_USRX+ 1
#define	IDC_NETWORK_USR			IDC_NETWORK_USRX+ 2
#define	IDC_NETWORK_PWD			IDC_NETWORK_USRX+ 3
#define	IDC_NETWORK_APNX		IDC_NETWORK_USRX+ 4
#define	IDC_NETWORK_APN			IDC_NETWORK_USRX+ 5
#define	IDC_NETWORK_PHONEX		IDC_NETWORK_USRX+ 6
#define	IDC_NETWORK_PHONE		IDC_NETWORK_USRX+ 7
#define	IDC_NETWORK_RETURN		IDC_NETWORK_USRX+ 8
#define	IDC_NETWORK_SET			IDC_NETWORK_USRX+ 9
#define	IDC_NETWORK_CONNECT		IDC_NETWORK_USRX+10
#define	IDC_NETWORK_OK			IDC_NETWORK_USRX+11
#define	IDC_NETWORK_CANCEL		IDC_NETWORK_USRX+12
#define	IDC_NETWORK_DISCONNECT		IDC_NETWORK_USRX+13
#define	IDC_NETWORK_CONNECT_CANCEL	IDC_NETWORK_USRX+14
#define	IDC_NETWORK_CLOSE         	IDC_NETWORK_USRX+15
#define	IDC_DONGLE_CLOSE		IDC_NETWORK_USRX+16



#define MEMOIREDAT					 "./data/memoire.dat"
#define BOMBTAXIS					 "./data/bombtaxis.dat"
#define MUSICLIST					 "./data/musiclist.dat"
#define TELDIAL						 "./data/teldial.dat"
#define TELNOGET					 "./data/telnoget.dat"
#define TELGET						 "./data/telget.dat"
#define NOTEPADDAT					 "./data/notepad.dat"
#define ALARMCLOCK					 "./data/alarmclock.dat"
#define TELBOOKDAT					 "./data/telbook.dat"
#define REGARDDAT					 "./data/regard.dat"
#define USERINFODAT					 "./data/userinfo.dat"
#define OUTBOX						 "./data/outbox.dat"
#define DRAFT						 "./data/draft.dat"
#define LASTTIME					 "./data/lastcall.dat"
#define CALLTIME					 "./data/calltime.dat"


void *gprs_read(void *data);
void *TaskBar(void *data);
void *TaskBarMenu(void *data);
void *MemoireAwork(void *data);
void *read_com(void *data);
void *ClockAwork(void *data);

#ifndef PH
#define EXTERN
#else
#define EXTERN       extern
#endif

EXTERN HWND hTaskBar;
EXTERN HWND hTaskBarMenu;
EXTERN HWND InputEdit;
EXTERN HWND hMainWnd;
EXTERN HWND BeCallingWnd;
EXTERN int  GPRSOFF;
EXTERN char becallnumber[30];

#include "lang.h"

#endif

